### ISSUE TITLE
Linguagem Utilizada

### ISSUE THREAD

**Issue by ForceTower** [matheustdo/paciencia-java#1]
Estou profundamente ofendido pela linguagem utilizada.

Kotlin >>>>>>>>>>>> Abismos >>>>>>>>>>>> Java

**Comment by matheustdo** [comment]
Fomos obrigados 😔

Peço-lhe desculpas pelo transtorno.

**Comment by ForceTower** [comment]
Kd o @ProfessorPadrõesFrameworks? Tem que parar essa doutrinação javista!
